Added LMGTFY command.
lenscas/thanks_bot_2 pull request #32
Opened 2020-10-05 20:47 UTC by harshhh-dev

Sends  a link for the user which sends them the answer.

2020-10-05 20:50 UTC, lenscas commented
I rather have the google command to do the search instead of LMGTFY. #23 :)

2020-10-05 20:51 UTC, harshhh-dev commented
Ok. I'll replace it then.

2020-10-05 20:55 UTC, lenscas commented on .gitignore
> +package-lock.json
what is this file and why is it suddenly inside the .gitignore file?

2020-10-05 21:05 UTC, lenscas requested changes

2020-10-05 21:05 UTC, lenscas commented on src/commands/oftenAsked/google.ts
> +    message.channel.send(`Find your answer at <https://www.google.com/search?q=search%3F%3F%3F%3F&oq=ho&aqs=chrome.0.69i59l3j35i39j69i57j69i60l3.7034j0j1&sourceid=chrome&ie=UTF-8>!`)
it doesn't use the search parameter? Also I'm pretty sure that those other get parameters can go.

2020-10-06 13:11 UTC, lenscas approved these changes

2020-10-06 13:11 UTC, merged